Mfa connector refactor
wso2-extensions/identity-oauth2-grant-mfa pull request #1
Opened 2023-06-27 07:53 UTC by DInuwan97

- Change the project structure.
- Use authentication context instead of direct user objects in Event Listeners.
- Enable file config capability to configure one custom authenticator.(This should have to improve based on removing hard-coded Basic authenticator and Identifier first step)
- Changes have done as per the recently finalized API Spec.
- Custom extensions are added to customize the MFA authentiacators based on user logged in attribute.
- Change the DAO layer and enable cache layers and implement a data peresistance layer.

2023-06-28 09:05 UTC, LahiruLS requested changes

2023-06-28 09:05 UTC, LahiruLS commented on components/org.wso2.carbon.identity.oauth2.grant.mfa.endpoints/src/main/java/org/wso2/carbon/identity/oauth2/grant/mfa/endpoints/impl/AuthenticationApiServiceImpl.java
> +                    .failureReason(failureReason);
In a successful case we do not have to set a failure reason. I remember @janakamarasena suggested that not to send null values in api response.

2023-07-03 08:50 UTC, rksk commented on components/org.wso2.carbon.identity.oauth2.grant.mfa.framework/src/main/java/org/wso2/carbon/identity/oauth2/grant/mfa/framework/util/Util.java
> +public class Util {
Shall we add a cool name here rather than just `Util`?

2023-07-03 08:52 UTC, rksk commented on components/org.wso2.carbon.identity.oauth2.grant.mfa.framework/src/main/java/org/wso2/carbon/identity/oauth2/grant/mfa/framework/internal/AuthenticationServiceComponent.java
> +		//mfaAuthListenerService.addAuthenticationListener(new AccountDisableListener());
Remove commented lines

2023-07-10 03:38 UTC, DInuwan97 commented
Continue in : https://github.com/wso2-extensions/identity-oauth2-grant-mfa/pull/2

2023-07-10 03:38 UTC, closed without merging